name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths-ignore: 
      - README.md
      - LICENSE
      - docs/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: |
          .sdlc/ci
          chmod +x .sdlc/*
